export const list = {
    RemoteFortressReader: {
        messages: [
            "MoveCommandParams",
            "MovementOption",
            "MenuContents",
            "MiscMoveParams",
            "SidebarState",
            "MenuItem",
            "SidebarCommand",
            "BuiildReqChoice",
            "BuildItemReq",
            "BuildSelector",
            "InstrumentFlags",
            "InstrumentPiece",
            "InstrumentRegister",
            "InstrumentDef",
            "Coord",
            "Tiletype",
            "TiletypeList",
            "BuildingExtents",
            "BuildingItem",
            "BuildingInstance",
            "RiverEdge",
            "RiverTile",
            "Spatter",
            "SpatterPile",
            "Item",
            "PlantTile",
            "TreeInfo",
            "PlantInstance",
            "MapBlock",
            "MatPair",
            "ColorDefinition",
            "MaterialDefinition",
            "BuildingType",
            "BuildingDefinition",
            "BuildingList",
            "MaterialList",
            "Hair",
            "BodySizeInfo",
            "UnitAppearance",
            "InventoryItem",
            "WoundPart",
            "UnitWound",
            "UnitDefinition",
            "UnitList",
            "BlockRequest",
            "BlockList",
            "PlantDef",
            "PlantList",
            "ViewInfo",
            "MapInfo",
            "Cloud",
            "WorldMap",
            "SiteRealizationBuildingWall",
            "SiteRealizationBuildingTower",
            "TrenchSpoke",
            "SiteRealizationBuildingTrenches",
            "SiteRealizationBuilding",
            "RegionTile",
            "RegionMap",
            "RegionMaps",
            "PatternDescriptor",
            "ColorModifierRaw",
            "BodyPartLayerRaw",
            "BodyPartRaw",
            "BpAppearanceModifier",
            "TissueRaw",
            "CasteRaw",
            "CreatureRaw",
            "CreatureRawList",
            "Army",
            "ArmyList",
            "GrowthPrint",
            "TreeGrowth",
            "PlantRaw",
            "PlantRawList",
            "ScreenTile",
            "ScreenCapture",
            "KeyboardEvent",
            "DigCommand",
            "SingleBool",
            "VersionInfo",
            "ListRequest",
            "Report",
            "Status",
            "ShapeDescriptior",
            "Language",
            "ItemImprovement",
            "ArtImageElement",
            "ArtImageProperty",
            "ArtImage",
            "Engraving",
            "FlowInfo",
            "Wave",
        ],
        methods: {
            GetSideMenu: ["EmptyMessage", "SidebarState"],
            SetSideMenu: ["SidebarCommand", "EmptyMessage"],
            GetMaterialList: ["EmptyMessage", "MaterialList"],
            GetGrowthList: ["EmptyMessage", "MaterialList"],
            GetItemList: ["EmptyMessage", "MaterialList"],
            GetBlockList: ["BlockRequest", "BlockList"],
            GetPlantList: ["BlockRequest", "PlantList"],
            GetUnitListInside: ["BlockRequest", "UnitList"],
            GetUnitList: ["EmptyMessage", "UnitList"],
            SetPauseState: ["SingleBool", "EmptyMessage"],
            GetPauseState: ["EmptyMessage", "SingleBool"],
            GetGameValidity: ["EmptyMessage", "SingleBool"],
            GetPartialCreatureRaws: ["ListRequest", "CreatureRawList"],
            GetPartialPlantRaws: ["ListRequest", "PlantRawList"],
            CheckHashes: ["EmptyMessage", "EmptyMessage"],
            GetTiletypeList: ["EmptyMessage", "TiletypeList"],
            GetViewInfo: ["EmptyMessage", "ViewInfo"],
            GetMapInfo: ["EmptyMessage", "MapInfo"],
            ResetMapHashes: ["EmptyMessage", "EmptyMessage"],
            GetBuildingDefList: ["EmptyMessage", "BuildingList"],
            GetWorldMap: ["EmptyMessage", "WorldMap"],
            GetWorldMapNew: ["EmptyMessage", "WorldMap"],
            GetRegionMaps: ["EmptyMessage", "RegionMaps"],
            GetRegionMapsNew: ["EmptyMessage", "RegionMaps"],
            GetCreatureRaws: ["EmptyMessage", "CreatureRawList"],
            GetWorldMapCenter: ["EmptyMessage", "WorldMap"],
            GetPlantRaws: ["EmptyMessage", "PlantRawList"],
            CopyScreen: ["EmptyMessage", "ScreenCapture"],
            PassKeyboardEvent: ["KeyboardEvent", "EmptyMessage"],
            SendDigCommand: ["DigCommand", "EmptyMessage"],
            GetVersionInfo: ["EmptyMessage", "VersionInfo"],
            GetReports: ["EmptyMessage", "Status"],
            MoveCommand: ["MoveCommandParams", "EmptyMessage"],
            JumpCommand: ["MoveCommandParams", "EmptyMessage"],
            MenuQuery: ["EmptyMessage", "MenuContents"],
            MovementSelectCommand: ["IntMessage", "EmptyMessage"],
            MiscMoveCommand: ["MiscMoveParams", "EmptyMessage"],
            GetLanguage: ["EmptyMessage", "Language"]
        }
    },
    dfproto: {
        messages: [
            "CoreTextFragment",
            "CoreTextNotification",
            "CoreErrorNotification",
            "EmptyMessage",
            "IntMessage",
            "IntListMessage",
            "StringMessage",
            "StringListMessage",
            "CoreBindRequest",
            "CoreBindReply",
            "CoreRunCommandRequest",
            "CoreRunLuaRequest",
            "EnumItemName",
            "BasicMaterialId",
            "BasicMaterialInfo",
            "BasicMaterialInfoMask",
            "JobSkillAttr",
            "ProfessionAttr",
            "UnitLaborAttr",
            "NameInfo",
            "NameTriple",
            "UnitCurseInfo",
            "SkillInfo",
            "UnitMiscTrait",
            "BasicUnitInfo",
            "BasicUnitInfoMask",
            "BasicSquadInfo",
            "UnitLaborState",
            "GetWorldInfoOut",
            "ListEnumsOut",
            "ListJobSkillsOut",
            "ListMaterialsIn",
            "ListMaterialsOut",
            "ListUnitsIn",
            "ListUnitsOut",
            "ListSquadsIn",
            "ListSquadsOut",
            "SetUnitLaborsIn",
        ],
        methods: {
            GetVersion: ["EmptyMessage", "StringMessage"],
            GetDFVersion: ["EmptyMessage", "StringMessage"],
            GetWorldInfo: ["EmptyMessage", "GetWorldInfoOut"],
            ListEnums: ["EmptyMessage", "ListEnumsOut"],
            ListJobSkills: ["EmptyMessage", "ListJobSkillsOut"],
            ListMaterials: ["ListMaterialsIn", "ListMaterialsOut"],
            ListUnits: ["ListUnitsIn", "ListUnitsOut"],
            ListSquads: ["ListSquadsIn", "ListSquadsOut"],
            SetUnitLabors: ["SetUnitLaborsIn", "EmptyMessage"],
            BindMethod: ["CoreBindRequest", "CoreBindReply"],
            RunCommand: ["CoreRunCommandRequest", "EmptyMessage"],
            CoreSuspend: ["EmptyMessage", "IntMessage"],
            CoreResume: ["EmptyMessage", "IntMessage"],
            RunLua: ["CoreRunLuaRequest", "StringListMessage"]
        }
    },
    isoworldremote: {
        messages: [
            "ColorDefinition",
            "EmbarkTileLayer",
            "EmbarkTile",
            "TileRequest",
            "MapRequest",
            "MapReply",
            "RawNames",
        ],
        methods: {
            GetEmbarkTile: ["TileRequest", "EmbarkTile"],
            GetEmbarkInfo: ["MapRequest", "MapReply"],
            GetRawNames: ["MapRequest", "RawNames"]
        }
    },
    rename: {
        messages: [
            "RenameSquadIn",
            "RenameUnitIn",
            "RenameBuildingIn",
        ],
        methods: {
            RenameSquad: ["RenameSquadIn", "EmptyMessage"],
            RenameUnit: ["RenameUnitIn", "EmptyMessage"],
            RenameBuilding: ["RenameBuildingIn", "EmptyMessage"]
        }
    }
}
